name: Event Emitter

on:
  schedule:
    # “At 00:00 on Sunday.” t. crontab.guru
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "OK"
