on:
  workflow_dispatch:
    inputs:
      sample_input_1:
        default: 123
      sample_input_2:
        default: 456

jobs:
  sample_needs:
    runs-on: ubuntu-latest
    steps:
      - run: echo Ok
  update:
    runs-on: ubuntu-latest
    needs: [ sample_needs ]
    strategy:
      matrix:
        sample_matrix_var_1: [ 1 ]
        sample_matrix_var_2: [ foo ]
    env:
      # github, env, job, jobs, steps, runner, secrets, strategy, matrix, needs, inputs
      CONTEXT_GITHUB: ${{ toJson(github) }}
      # CONTEXT_ENV: ${{ toJson(env) }}
      CONTEXT_JOB: ${{ toJson(job) }}
      CONTEXT_JOBS: ${{ toJson(jobs) }}
      CONTEXT_STEPS: ${{ toJson(steps) }}
      CONTEXT_RUNNER: ${{ toJson(runner) }}
      CONTEXT_SECRETS: ${{ toJson(secrets) }}
      CONTEXT_STRATEGY: ${{ toJson(strategy) }}
      CONTEXT_MATRIX: ${{ toJson(matrix) }}
      CONTEXT_NEEDS: ${{ toJson(needs) }}
      CONTEXT_INPUTS: ${{ toJson(inputs) }}
    steps:
      - run: env
